# Generated by Django 6.0.6 on 2026-06-08 18:20

import django.db.models.deletion
import laporan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_laporan', models.CharField(blank=True, max_length=20, unique=True)),
                ('foto', models.ImageField(upload_to=laporan.models.report_upload_path, verbose_name='Foto Laporan')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Laporan')),
                ('alamat', models.CharField(max_length=255, verbose_name='Alamat / Lokasi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('kategori', models.CharField(choices=[('jalan', '🛣️ Jalan Rusak'), ('sampah', '🗑️ Tumpukan Sampah'), ('lampu', '💡 Lampu Jalan Mati'), ('lainnya', '📋 Lainnya')], default='lainnya', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('darurat', 'Darurat')], default='sedang', max_length=20)),
                ('ai_kategori', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kategori AI')),
                ('ai_confidence', models.IntegerField(default=0, verbose_name='Confidence AI (%)')),
                ('catatan_admin', models.TextField(blank=True, verbose_name='Catatan Admin')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Lapor')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diperbarui')),
                ('diselesaikan_pada', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_set', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='AktivitasLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('warna', models.CharField(default='primary', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='laporan.laporan')),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pesan', models.CharField(max_length=255)),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laporan.laporan')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
