# Generated by Django 5.2.15 on 2026-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('jalan', 'Jalan Rusak'), ('sampah', 'Tumpukan Sampah'), ('lampu', 'Lampu Jalan Mati'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
    ]
